### ISSUE TITLE
Unable to run the script

### ISSUE THREAD

**Issue by GunpreetAhuja** [sola-da/StaticBugCheckers#1]
Hi, I got this error while running the script:

grep: /proc/cpuinfo: No such file or directory
./scripts/config.sh: line 19: * 2/3: syntax error: operand expected (error token is "* 2/3")

**Comment by andrewhabib** [comment]
Hi, 

Line 19 in ./scripts/config.sh tries to figure out the number of available cores on your machine to utilize multi-cores efficiently. It uses simple bash syntax to do so.
However, you can just set the JOBS variable manually, for instance, JOBS=1; if the command fails for a reason or another.

**Comment by GunpreetAhuja** [comment]
Thanks,
There is another error that say: 
>>> Switching from master to pr #112
fatal: Refusing to fetch into current branch refs/heads/extendedD4J of non-bare repository

and a next one:
>>> Checking out and compiling the dataset
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]


yet another:
>>> Running the static checkers on the buggy versions from the Defects4j <<<
>>> Running Error Prone
Traceback (most recent call last):
  File "/Users/stylethinking/StaticBugCheckers/python/RunErrorprone.py", line 51, in <module>
    path_d4j_projects = os.path.join(os.getcwd(), sys.argv[2])
IndexError: list index out of range

can you give me the reason behind this?

**Comment by andrewhabib** [comment]
Hi again, 

The type of errors you are receiving are quite unexpected. What OS are you running the scripts on?

All the scripts in this repository are developed and tested on Ubuntu (I suppose most major Linux distributions should also work fine).

**Comment by GunpreetAhuja** [comment]
It's Mac

**Comment by andrewhabib** [comment]
ahaaa, I see now. 

Most - if not all - of the errors you are getting are due to the different kernel and supported commands on MacOS vs Ubuntu. 

You have to either adapt the shell scripts to use corresponding commands supported by the MacOS or, you can run the python scripts directly, but manually. Basically shell scripts are just meant to automate the running of python scripts!

**Comment by GunpreetAhuja** [comment]
Hi Thanks ,I tried it on Linux but it is showing the error readlink: missing operand at the step checking out and compiling the dataset.

**Comment by GunpreetAhuja** [comment]
Hi I resolved the above error and the script runs completely. However, I am getting empty files in the study folder. Do you have any idea which scripts might not be working? There is no error displayed on the terminal when we run the main script.

**Comment by andrewhabib** [comment]
Maybe your fix of readlink error is not working and that would result in the tools not running properly on the dataset?... which will eventually mean that you get empty results in the study folder? 

I'd debug the following:
- First, make sure that the static checkers are downloaded properly by inspecting the static-checkers/ folder
- Second, double check that the d4j dataset is cloned, instantiated, and all projects are checked-out properly (defects4j/projects/ should have two sub-folders b/ and f/ where each should include all checked-out buggy and fixed versions, respectively)
- Third, make sure that your fix of readlink in run_checkers_on_defects4j.sh script is working that the script obtains proper path of each static analyzer

**Comment by GunpreetAhuja** [comment]
Thanks, I am trying this.

**Comment by andrewhabib** [comment]
Hi again, 

I managed to get my hands on a Mac Book. Now, all scripts support MacOS and are supposed to run smoothly on Linux and Mac. 
Please read the requirements section carefully to make sure your system has all necessary dependencies. 

Let me know if it works so that I can close this issue :)

**Comment by GunpreetAhuja** [comment]
Hi thanks, It is working (in progress)

**Comment by andrewhabib** [comment]
Great! I will then close this issue :)
